#!/usr/bin/env bash
###############################################################################
# A script to report the state of CrowdStrike Falcon (thanks, ZT and mrw!)    #
# - If CrowdStrike Falcon is not installed, "Not Installed" will be returned. #
# scriptVersion="0.0.13"                                                      #
###############################################################################

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/
RESULT="Failed: Not Installed"
lastConnectionFailed="false"

# The number of days before reporting device has not connected to the CrowdStrike Cloud.
lastConnectedVariance="7"

# The date format expected from date fields generated by `falconctl`.
falconctl_date_format="%b %d %Y %H:%M:%S"

# The alternate date format generated by `falconctl` when AM/PM values are included.
falconctl_ampm_date_format="%b %d %Y %I:%M:%S %p"

# The number of times to try `falconctl` when the Falcon service is temporarily unavailable.
falconctlRetryAttempts="3"

# The number of seconds to pause between `falconctl` retry attempts.
falconctlRetryPause="5"



###
# Pre-flight: Check the Locale; this will affect the output of falconctl stats
###

lib_locale=$( /usr/bin/defaults read "/Library/Preferences/.GlobalPreferences.plist" AppleLocale )
root_locale=$( /usr/bin/defaults read "/var/root/Library/Preferences/.GlobalPreferences.plist" AppleLocale )

if [[ "${lib_locale}" != "en_US" ]]; then
    /usr/bin/defaults write "/Library/Preferences/.GlobalPreferences.plist" AppleLocale "en_US"
fi

if [[ "${root_locale}" != "en_US" ]]; then
    /usr/bin/defaults write "/var/root/Library/Preferences/.GlobalPreferences.plist" AppleLocale "en_US"
fi



###
# Functions
###

fixup_date_string(){
    # Convert unicode spaces in a string into a basic space
    # Arguments
    # $1 = (str) a string

    /usr/bin/sed 's/,//g; s/ at//g; s/[[:space:]]/ /g; s/^ //; s/ $//;' <<< "${1}"
}

get_time_stamp() {
    # Helper function to provide a standard date-time stamp
    # Arguments
    # --format | -f = (str) Date output format to use; otherwise the default will be used
    # --adjust | -a = (str) Modify the date (e.g. future/past)
    # --epoch | -e = (str) Output date in epoch format
    local date_format
    local args
    declare -a args

    if
        printf '%s\n' "$@" | grep --extended-regexp --line-regexp --quiet "\-f|\-\-format" && \
        printf '%s\n' "$@" | grep --extended-regexp --line-regexp --quiet "\-e|\-\-epoch" \
    ; then
        echo "[Error] Unable to pass both --format and --epoch parameters"
        exit 200
    fi

    # Loop through the passed arguments
    while (( "$#" )); do
        case "${1}" in
            --format | -f )
                shift
                local date_format="${1}"
            ;;
            --adjust | -a )
                shift
                args+=("'${1}'")
            ;;
            --epoch | -e )
                local epoch="true"
                args+=("+%s")
            ;;
            * )
                echo "[Warning] Unsupported parameter passed to \`get_time_stamp()\`"
                exit 200
            ;;
        esac
        shift
    done

    if [[ -z "${date_format}" && -z "${epoch}" ]]; then
        date_format="${falconctl_date_format}"
    fi

    if [[ -n "${date_format}" ]]; then
        args=( "'${date_format}'" "${args[@]}")
    fi

    # shellcheck disable=SC2294
    eval /bin/date -j "${args[@]}"
}

convert_date(){
    # Convert a formatted date string into another format
    # Arguments
    # $1 = (str) a date in string format
    # $2 = (str) the input format of the date string
    # $3 = (str) the output format of the date string
    local date_string="${1}"
    local input_format="${2}"
    local output_format="${3}"
    local fixed_date

    if [[ -n "${date_string}" ]]; then
        fixed_date="$( fixup_date_string "${date_string}" )"

        case "${fixed_date}" in
            *" AM" | *" PM" )
                /bin/date -j -f "${falconctl_ampm_date_format}" "${fixed_date}" +"${output_format}" 2>/dev/null || \
                /bin/date -j -f "${input_format}" "${fixed_date}" +"${output_format}" 2>/dev/null
                ;;
            * )
                /bin/date -j -f "${input_format}" "${fixed_date}" +"${output_format}" 2>/dev/null || \
                /bin/date -j -f "${falconctl_ampm_date_format}" "${fixed_date}" +"${output_format}" 2>/dev/null
                ;;
        esac
    fi
}

is_integer() {
    # Test if a string is a valid integer.
    # Arguments
    # $1 = (str) value to test

    [[ "${1}" =~ ^-?[0-9]+$ ]]
}

check_last_connection() {
    # Check if the last connected date is older than seven days.
    # Arguments
    # $1 = (str) date formatted string, captured from 
        # the `falconctl stats Communications` "last connected date" attribute
    # $2 = (int) number (of days)
    local connectionEpoch
    local staleConnectionEpoch

    connectionEpoch="$( convert_date "${1}" "${falconctl_date_format}" "%s" )"
    staleConnectionEpoch="$( get_time_stamp --adjust -v-"${2}"d --epoch )"

    if ! is_integer "${connectionEpoch}"; then
        returnResult+="Last Connected: Unable to parse ${1};"
        lastConnectionFailed="true"
    elif [[ "${connectionEpoch}" -lt "${staleConnectionEpoch}" ]]; then
        returnResult+="Last Connected: ${1} (older than ${2} days);"
        lastConnectionFailed="true"
    else
        returnResult+="Last Connected: ${1};"
    fi
}

clean_result_string() {
    # Collapse multi-line command output into one Jamf-friendly result line.
    # Arguments
    # $1 = (str) string to collapse

    /usr/bin/tr '\r\n' '  ' <<< "${1}" | /usr/bin/sed 's/[[:space:]][[:space:]]*/ /g; s/^ //; s/ $//'
}

read_plist_value() {
    # Safely read a value from plist data without leaking parser errors.
    # Arguments
    # $1 = (str) PlistBuddy path
    # $2 = (str) plist data

    "${plistBuddyBinary}" -c "Print ${1}" /dev/stdin <<< "${2}" 2>/dev/null
}

is_plist_readable() {
    # Test if the falconctl output can be parsed as plist data.
    # Arguments
    # $1 = (str) plist data

    [[ -n "${1}" ]] && "${plistBuddyBinary}" -c 'Print :' /dev/stdin <<< "${1}" >/dev/null 2>&1
}

get_falcon_agent_stats() {
    # Run falconctl with retries for temporary daemon communication errors.
    local falconctlAttempt

    for (( falconctlAttempt = 1; falconctlAttempt <= falconctlRetryAttempts; falconctlAttempt++ )); do
        falconAgentStats=$( "${falconBinary}" stats -p agent_info Communications CloudInfo 2>&1 )

        if is_plist_readable "${falconAgentStats}"; then
            return 0
        fi

        if [[ "${falconctlAttempt}" -lt "${falconctlRetryAttempts}" ]]; then
            /bin/sleep "${falconctlRetryPause}"
        fi
    done

    return 1
}




###
# Program
###

falconBinary="/Applications/Falcon.app/Contents/Resources/falconctl"
plistBuddyBinary="/usr/libexec/PlistBuddy"

if [[ ! -x "${falconBinary}" ]]; then
    echo "${RESULT}"
    exit 0
fi

if ! get_falcon_agent_stats; then
    RESULT="Error: $( clean_result_string "${falconAgentStats}" )"
    echo "${RESULT}"
    exit 0
fi

# Get the sensor operational status
sensorOperational=$( read_plist_value '":agent_info:sensor_operational"' "${falconAgentStats}" )
# echo "sensorOperational: ${sensorOperational}"

# Get the connection established dates
connectionState=$( read_plist_value '":CloudInfo:State"' "${falconAgentStats}" )
# echo "connectionState: ${connectionState}"

established=$( read_plist_value '":Communications:Communication:Cloud Activity:Established At"' "${falconAgentStats}" )
# echo "established: ${established}"

lastEstablished=$( read_plist_value '":Communications:Communication:Cloud Activity:Last Established At"' "${falconAgentStats}" )
# echo "lastEstablished: ${lastEstablished}"

if [[ "${connectionState}" == "connected" ]]; then

    # Compare if both were available.
    if [[ -n "${established}" ]] && [[ -n "${lastEstablished}" ]]; then

        establishedEpoch="$( convert_date "${established}" "${falconctl_date_format}" "%s" )"
        lastEstablishedEpoch="$( convert_date "${lastEstablished}" "${falconctl_date_format}" "%s" )"

        # Check which is more recent when the dates can be parsed.
        if is_integer "${establishedEpoch}" && is_integer "${lastEstablishedEpoch}" && [[ "${establishedEpoch}" -ge "${lastEstablishedEpoch}" ]]; then
            testConnectionDate="${established}"
        elif is_integer "${lastEstablishedEpoch}"; then
            testConnectionDate="${lastEstablished}"
        elif is_integer "${establishedEpoch}"; then
            testConnectionDate="${established}"
        else
            returnResult+=" Unknown Connection State;"
            lastConnectionFailed="true"
        fi

        # Check if the more recent date is older than seven days
        if [[ -n "${testConnectionDate}" ]]; then
            check_last_connection "${testConnectionDate}" "${lastConnectedVariance}"
        fi

    elif [[ -n "${established}" ]]; then
        # If only the Established date was available, check if it is older than seven days.
        check_last_connection "${established}" "${lastConnectedVariance}"
    elif [[ -n "${lastEstablished}" ]]; then
        # If only the Last Established date was available, check if it is older than seven days.
        check_last_connection "${lastEstablished}" "${lastConnectedVariance}"
    else
        # If no connection date was available, return disconnected
        returnResult+=" Unknown Connection State;"
        lastConnectionFailed="true"
    fi

elif [[ -n "${connectionState}" ]]; then
    # If no connection date was available, return state
    returnResult+=" Connection State: ${connectionState};"
fi

if [[ "${sensorOperational}" == "true" ]]; then
    if [[ "${lastConnectionFailed}" == "true" ]]; then
        RESULT="Failed: ${returnResult%;}"
    else
        RESULT="Running; ${returnResult%;}"
    fi
else
    case ${falconAgentStats} in

        *"status.bin"* )
            RESULT="Failed: 'status.bin' NOT found; ${returnResult}"
            ;;
        *"No such file"* )
            RESULT="Not Installed; ${returnResult}"
            ;;
        *"Error"* )
            RESULT="Error: ${falconAgentStats}; ${returnResult}"
            ;;
        * )
            RESULT="Unknown Error: ${returnResult}"
            ;;

    esac
fi

echo "${RESULT}"

exit 0
